In [1]:
print("hello")

hello


In [3]:
import numpy as np
print(np.__version__)


2.1.3


In [5]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr1=np.full((3,3),True,dtype=bool)
print(arr1)
arr2=np.full((3,3),True,dtype=bool)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

In [8]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
import numpy as np

arr = np.arange(10)
arr.reshape(2, -1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]


array([ 6,  9, 10])

In [11]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
arr[:, [1, 0, 2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [12]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
arr[[1, 0, 2], :]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [14]:

import numpy as np

arr = np.array([1.123456, 2.987654, 3.141592])
np.set_printoptions(precision=3)
print(arr)



[1.123 2.988 3.142]


In [15]:
import numpy as np

rand_arr = np.random.random([5, 3])
np.set_printoptions(precision=3)
rand_arr[:4]


array([[0.122, 0.941, 0.911],
       [0.828, 0.139, 0.806],
       [0.034, 0.269, 0.598],
       [0.603, 0.082, 0.097]])

In [16]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.intersect1d(a, b)
c


array([2, 4])

In [17]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
c = np.setdiff1d(a, b)
c


array([1, 2, 3, 4])

In [18]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.where(a == b)


(array([1, 3, 5, 7]),)

In [19]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]


array([ 6,  9, 10])

In [21]:
import numpy as np
array_values = np.array([[12,45,23],[67,34,89]])
total_sum = np.sum(array_values)
print("numpy array:\n",array_values)
print("\nsum of all vlaues in the array:", total_sum)

numpy array:
 [[12 45 23]
 [67 34 89]]

sum of all vlaues in the array: 270


In [24]:
import numpy as np

array_floats = np.random.rand(2, 3, 4)
print("3D numpy array with random floating-point number:\n",array_floats)

3D numpy array with random floating-point number:
 [[[0.604 0.619 0.382 0.835]
  [0.454 0.253 0.401 0.18 ]
  [0.083 0.76  0.007 0.101]]

 [[0.612 0.248 0.925 0.502]
  [0.948 0.071 0.243 0.801]
  [0.065 0.608 0.356 0.481]]]


In [25]:
import numpy as np
array_values = np.array([[12, 45, 23], [67, 34, 89]])
max_value = np.max(array_values)
print("NumPy Array:\n", array_values)
print("\nMaximum Value in the Array:", max_value)


NumPy Array:
 [[12 45 23]
 [67 34 89]]

Maximum Value in the Array: 89


In [26]:
import numpy as np
array_values = np.array([[12, 45, 23], [67, 34, 89]])
min_value = np.min(array_values)
print("NumPy Array:\n", array_values)
print("\nMinimum Value in the Array:", min_value)


NumPy Array:
 [[12 45 23]
 [67 34 89]]

Minimum Value in the Array: 12


In [27]:
import numpy as np

array_values = np.array([[12, 45, 23], [67, 34, 89]])
median_value = np.median(array_values)
print("NumPy Array:\n", array_values)
print("\nMedian Value of the Array:", median_value)


NumPy Array:
 [[12 45 23]
 [67 34 89]]

Median Value of the Array: 39.5


In [28]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(array1, array2)

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nDot Product Result:\n", dot_product)


Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Dot Product Result:
 [[19 22]
 [43 50]]


In [29]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

cross_product = np.cross(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("\nCross Product Result:", cross_product)


Array 1: [1 2 3]
Array 2: [4 5 6]

Cross Product Result: [-3  6 -3]


In [30]:
import numpy as np

array = np.array([[4, 7], [2, 6]])

inverse = np.linalg.inv(array)

print("Original Array:\n", array)
print("\nInverse of the Array:\n", inverse)


Original Array:
 [[4 7]
 [2 6]]

Inverse of the Array:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [32]:
import numpy as np

a = np.array([1, 2, 3, 4])
reversed_a = a[::-1]

print("Original Array:", a)
print("Reversed Array:", reversed_a)


Original Array: [1 2 3 4]
Reversed Array: [4 3 2 1]


In [33]:
import numpy as np

array = np.array([[4, 6], [3, 8]])

determinant = np.linalg.det(array)

print("Original Array:\n", array)
print("\nDeterminant of the Array:", determinant)


Original Array:
 [[4 6]
 [3 8]]

Determinant of the Array: 14.000000000000004


In [34]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.hstack((a,b))
result1 = np.vstack((a,b))
print(result)
print(result1)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
import numpy as np

arr = np.array([ 3, 1, 4,2])
sorted_arr = np.sort(arr)

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)


Original Array: [3 1 4 2]
Sorted Array: [1 2 3 4]


In [37]:
import numpy as np

arr = np.array([[ 3, 1, 4,2],[7,8,2,0]])
sorted_arr = np.sort(arr)

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)


Original Array: [[3 1 4 2]
 [7 8 2 0]]
Sorted Array: [[1 2 3 4]
 [0 2 7 8]]


In [39]:
import numpy as np  

arr = np.array([[3,1,4,2],[0,9,2,5]]) 
sorted_arr = np.sort(arr)[::-1] 
print("Original Array:", arr)
print("Descending Sorted Array:", sorted_arr) 

Original Array: [[3 1 4 2]
 [0 9 2 5]]
Descending Sorted Array: [[0 2 5 9]
 [1 2 3 4]]
